### ISSUE TITLE
Windows + Firefox @ 127.0.0.1:8080 :: invalid request

### ISSUE THREAD

**Issue by azev** [Artificial-University/adblock-proxy#5]
http://i.imgur.com/cMcmk8z.png
Any help with this please?

**Comment by martensms** [comment]
Hey, the server itself is not responding with an 'Invalid Request" response, so the issue is somewhere else. I'm using Ubuntu, but in Firefox I'm using these settings (just for verification): http://i.imgur.com/SMryR0k.png

I also selected "Use proxy for all requests", just to be sure it's always used directly.

Could you try debugging it using

1. Right Click
2. Select Inspect Element
3. Select Network Tab
4. Then Reload the page

... and look for the initial request and post its response headers? That might give some insights there.

It should look similar to this screenshot here: http://i.imgur.com/ysrkx1L.png

Note that there's the Request URL and a different Remote address. The Remote Address has to be 127.0.0.1:8080, otherwise the Browser didn't use the Proxy and there *might be* an extension or addon preventing proxy usage.

**Comment by azev** [comment]
Hello.
I'm using a clean firefox profile for this purpose (no addons are being used)
http://i.imgur.com/tfF6KXI.png

I think the problem is nodejs is not even listening to 127.0.0.1:8080 (see the red line on the screenshot.
If I browse to http://127.0.0.1:8080 i get the same "invalid request"

I tested nodejs listening to 8081 and answering 'hello world' and it works.
http://127.0.0.1:8081

---> hello world

**Comment by martensms** [comment]
Can you post the detail view? There I can see the request and response headers. You can open the detail view by clicking on the request entry of "/".

**Comment by azev** [comment]
Sure! 
http://i.imgur.com/H5dUqs6.png
I have some skills on Javascript and I''d like to contribute. However I don't understand how github works (it is so confusing!) How Can I contribute?

Look at the screenchot where it says `HTTP Proxy created on null:8080`
see... ----> null

**Comment by cookiengineer** [comment]
The update from today made it clear that this issue was/is related to Redirects. So I'm opening up a new issue that keeps track of Redirects and the missing Featureset for a complete release.
