### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by wastez** [Artificial-University/adblock-proxy#6]
I got the following error on startup: (Also if i add --protocol=http)

fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/opt/adproxy/lib/protocol/../../cert.pem'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at /opt/adproxy/lib/protocol/HTTPS.js:20:19
    at Object.<anonymous> (/opt/adproxy/lib/protocol/HTTPS.js:197:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by martensms** [comment]
Phew, I need to dig into this first. I'll probably do a packaged variant of the project, so it's easier to install and get up and running.

**Comment by vdergachev** [comment]
Hi there, i got same problem.
Is there are any solution or workaround?

**Comment by wastez** [comment]
The cert path isn´t correct in the source code.

**Comment by martensms** [comment]
Jep, I'm working at a fix atm. I'll push up some deb packages today evening or tomorrow for the releases section - with https and http defaults, so certificates get automatically generated on installation.

**Comment by hpincket** [comment]
How is the cert.pem used? I found a command to generate a self-signed certificate, but beyond generating it I'm ignorant. Thanks.

**Comment by martensms** [comment]
@hpincket The cert.pem is used for the https proxy as it requires a valid cert. I could not yet dig into letsencrypt - which would be the preferred way to generate SSL certs.

For now, I worked on the https://github.com/LazerUnicorns/adblock-proxy/tree/refactor branch, but I couldn't manage to get the HTTPS proxy up and running properly. Many issues, such as Browser denying the test certs from CAcert (not shipped as root cert on many distros) et al.

The test certificates were generated using openssl, but they are, of course, denied by the browsers and viewed as an untrusted SSL cert there:

`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem;`

That's why I think HTTPS proxying will not be possible until letsencrypt is live :-/ In the refactor branch I disabled the HTTPS proxy and only activated the HTTP proxy. I'm currently still testing and fixing some minor rule issues / domain filters, if that is working properly, I'll push out the deb / exe / zip files to the releases section with the proper iojs binary bundled.

**Comment by Nepoxx** [comment]
Any update on this? Letsencrypt is in public beta :D

**Comment by cookiengineer** [comment]
We can't use letsencrypt because the Proxy is running locally and therefore is not reachable via the internet. So the openssl usage for HTTPS is impossible to workaround and will always by concept be a requirement (snakeoil cert workflow).
