### ISSUE TITLE
socks5 proxy

### ISSUE THREAD

**Issue by Eibwen** [Artificial-University/adblock-proxy#8]
Your readme/usage says socks5 is supported, but when i try it i get the following:

```
>$ node ./bin/proxy --port=8080 --public=false --protocol=socks5
{ host: '127.0.0.1',
  port: 8080,
  protocol: 'socks5',
  public: false }
/adblock-proxy/lib/Proxy.js:92
                protocol.create(host, port, _is_blocked, this);
                         ^
TypeError: undefined is not a function
    at Object.Proxy.create (/adblock-proxy/lib/Proxy.js:92:14)
    at /adblock-proxy/bin/proxy:62:8
    at Object.<anonymous> (/adblock-proxy/bin/proxy:65:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by martensms** [comment]
The socks5 protocol adapter is not supported anymore. I simply have no time to implement it at the moment. I am totally busy pushing out a bundle so that people can have a reproducible environment - as nodejs/iojs/node binary setup et all are totally pain to debug.

Anyone that has time and wants to rewrite the socks5 adapter is welcome to do so. If you need help, just let me know.

Currently, adblock proxy also only has support for HTTP, because you need a valid (cross-signed) cert for the browser in order to have HTTPS/SSL support. This can only be implemented once letsencrypt support is in. Letsencrypt is still not stable and still has not a valid cross-signed cert among all browsers, so that is blocking for the HTTPS stuff because it's impossible to debug.

Please take a look at [issue 7](https://github.com/LazerUnicorns/adblock-proxy/issues/7) that explains how to get the current refactor builds.

**Comment by Eibwen** [comment]
Ah, thank you for the prompt reply.  I would take a shot at it, but don't have much free time lately, and have no clue about any aspect of socks5 proxies...

Either way, this project is great.  

(off topic)
Have you looked at Privoxy at all, since porting some aspects of adaptors and protocols might be easier than writing it from docs, at least for alpha and/or proof-of-concept versions.

**Comment by cookiengineer** [comment]
This is somehow an uber-late reply to the issue, but to keep things up-to-date I'm gonna write here anyways.

As of the major refactor today the proxy now respects locally running SOCKS5 proxies that are configured globally. That means TOR support is now in, and the Adblock Proxy runs "in between" HTTP/HTTPS and connects to the TOR Proxy to make requests to the outside WAN.

So SOCKS5 Support isn't required and only HTTP/HTTPS Support is required for this project to run properly with Privoxy/Vidalia/TOR et al - and this issue can be closed.
