### ISSUE TITLE
Page is not working when i try to load with the proxy

### ISSUE THREAD

**Issue by lucas59356** [Artificial-University/adblock-proxy#9]
![image](https://cloud.githubusercontent.com/assets/15693688/21082377/72c089d4-bfc1-11e6-84b8-2b3da9fc3ee5.png)

I dont know why but the browser are not loading the pages when i configure to use the proxy, the port in the command line is the same as i configured.
Windows 7 Professional
Chrome 57 32bit
Node 7.2.1

**Comment by cookiengineer** [comment]
Gonna reply tomorrow when I have more time. Just letting you know that I'll dig into it.

**Comment by cookiengineer** [comment]
Okay, so I did a major refactor from scratch to come around the architectural issues. Everything is now built with lychee.js and the host files support is back and ready.

I had to do a rebase because of hard structural changes to the folders and files, so you need to re-clone again this time.

```bash
cd /path/to/adblock-proxy;

# node v7+ with ES6 support required
node ./bin/proxy.js --port=1338; # change port accordingly
```

I did some initial testing with surfing around `stackoverflow.com` and `reddit.com` and it seems to work. Remember that HTTPS support is not yet in (and needs some work with the node request API, have no idea for now on how to solve this).

So just make sure that you have no Browser extension forcing you to load HTTPS websites to verify that the new Proxy is working on your system.

Websites I successfully tested:

```bash
http://artificial.engineering (IPv4)
http://artificial.university (IPv4)
http://cookie.engineer (IPv4)
http://stackoverflow.com (IPv6)
http://reddit.com (IPv4)
```

A cool feature is now that you can also use TOR as a system-wide proxy, because the new architecture will respect system-wide proxies <3

I'm not yet sure if the new cache works in every case (regarding REST APIs and stuff), but I'm opening some other issues for that to keep track of it.

**Comment by cookiengineer** [comment]
Update: Adblock Plus Filter Lists are integrated now.

**Comment by cookiengineer** [comment]
@lucas59356 Please respond whether that helped you or not.

**Comment by lucas59356** [comment]
Sorry, I had migrated to privoxy, the integration  is more natural in my
windows PC.

Em qua, 4 de jan de 2017 17:40, Cookie Engineer <notifications@github.com>
escreveu:

**Comment by cookiengineer** [comment]
Okay :) Then I'll close this issue.
